### ISSUE TITLE
due maggiori

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/iterazione_c#4]
algoritmo errato

**Comment by FabioZTessitore** [comment]
esempio di dati che non vanno
3, 4, 2, 2, 2, 2, 2, 2, 2, 2

**Comment by tonyiovino** [comment]
immaginavo...

**Comment by tonyiovino** [comment]
Il problema non lo fa più

**Comment by FabioZTessitore** [comment]
il problema non si vede ma c'è. Nel primo else if fai un confronto che funziona solo per caso
