### ISSUE TITLE
quadrato

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/iterazione_c#5]
non hai aggiornato il gitignore

la stampa dei caratteri può essere effettuata con `putchar()`

devi rivedere un po' le variabili e il modo in cui le usi per i cicli. Il codice funziona ma non è per niente chiaro

**Comment by FabioZTessitore** [comment]
va un po' meglio, ma ancora risulta poco chiaro. Le variabili `larghezza` e `altezza` (come `x` e `y`) danno l'idea di essere l'altezza e la larghezza **corrente**.

es. immaginiamo di aver stampato

```
######
###
```

`altezza` potrebbe essere `1` (partendo da 0) e `larghezza` potrebbe essere 2.

Detto questo un algoritmo più semplice da seguire potrebbe essere:

1. `lato = 6`
1. `altezza = 0`
1. finché altezza non arriva a `lato`:
    1. `larghezza = 0`
    1. Stampa finché `larghezza` è inferiore a `lato`


PS. Ti ricordo che le stampe avvengono per righe. Quindi si stampa prima una `larghezza`, poi si va a capo e se ne stampa un'altra. Il tutto per `altezza` volte (hai usato le variabili al contrario)

**Comment by tonyiovino** [comment]
Ah, ho capito.

**Comment by tonyiovino** [comment]
Credo di aver fatto bene ora

**Comment by tonyiovino** [comment]
Il mio intento era quello di stampare prima la larghezza e poi l'altezza. Pensavo che l'ordine era giusto
