### ISSUE TITLE
quadrato vuoto

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/iterazione_c#6]
non hai aggiornato il gitignore

il codice è complicato e non si capisce cosa fa

**Comment by FabioZTessitore** [comment]
non funziona quando il lato è 1

**Comment by tonyiovino** [comment]
E allora la devo mettere una if alla fine... Hahaha

Il Mar 28 Lug 2020, 13:56 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
va molto meglio, ma resta il problema del lato 1
