### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/iterazione_c#7]
perché si chiama cerchio2?
cmq non lo hai aggiunto al gitignore

inoltre per varaibili in vingola mobile singole (non vettori) è meglio usare double. In ogni caso prima della stampa i float sono convertiti a double automaticamente

**Comment by tonyiovino** [comment]
fatto

**Comment by FabioZTessitore** [comment]
non ci siamo ancora. Bisogna essere precisi.

1. nel gitignore devi mettere il nome del file da ignorare che è cerchio2 e non cerchio
1. quando si fa l'input dei double si usa %lf non %f. Per la stampa va bene %f sia per double che per float perché come ti dicevo i float sono convertiti a double
